apiVersion: v1
kind: Pod
metadata:
  name: clic-driver
  namespace: argo
spec:
  containers:
  - name: clic-driver
    image: clic-driver:v0
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    args:
    - java -jar clic-driver.jar
    volumeMounts:
      - name: nfs-volume
        mountPath: /data
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: pvc-nfs